### ISSUE TITLE
Singular matrix when running on computing cluster

### ISSUE THREAD

**Issue by awellaye** [Rjacobucci/regsem#10]
Hi Ross, 

I am fitting a unified SEM model with lasso regulation using the function 'cv_regsem'. A quite strange thing was that the model run very normally on any local computer I tried, but when I switched to my university's computing cluster for my simulation runs, I started getting the following error message of singular matrix.  I requested the same R version module on the cluster, I don't quite understand what caused the difference.  I wonder if you have any experience of this.  Let me know if you'd like to see additional information. And I appreciate your insight in advance!

Below is the error message I got ONLY when using the cluster:

error: inv(): matrix seems singular
Error in rcpp_fit_fun(ImpCov = mult$ImpCov, SampCov, type2, lambda, gamma,  : 
  inv(): matrix seems singular
Calls: cv_regsem -> regsem

**Comment by Rjacobucci** [comment]
That behavior seems to happen really randomly on Linux (i'm guess what that is what your cluster uses). I have no idea why and have seen this behavior in some situations.

It doesn't seem to have a real cause, therefore I would suggest building try() into your repetitions, then running say 210 replications if you want 200 results. 

Sorry for not having a more tangible solution.

**Comment by awellaye** [comment]
Thank you for your instant response. Yes, you are right, it is Linux. That is helpful, I wasn't sure if I made any mistake with the model, glad it does not sound so.  In that case, I wonder if it has to do with the default tolerance for non-positive definite, if so, would it be helpful to raise up the tolerance level in Linux?  Raising up the number if trials work for me if there was no cure for it.

**Comment by Rjacobucci** [comment]
I agree that raising the tolerance specifically for these sorts of situations would be a good idea. I'm currently traveling but will look into this when I get back. If you have any ideas as to which pieces of the C++ could be altered, let me know. I'll leave the issue open til then. Thanks for pointing this out! I wasn't sure how often this occurred.

**Comment by FlorianScharf** [comment]
I suggested a fix in a pull request. I am currently testing it and it seems to get rid of the error and I don't observe any unexpected distortions. 

Keen to hear your opinion.
