### ISSUE TITLE
Regsem with missing data

### ISSUE THREAD

**Issue by B260198** [Rjacobucci/regsem#19]
Dear Prof. Jacobucci,

I encountered some difficulties when using regsem with missing data: If I fit a sem with many missing values and then want to regularize this model using the cv_regsem function , the fit indices at lambda = 0 differ from the fit indices of the original model.  In the following minimal example I have inserted missings into a dataset, fitted a sem model and regularized it using the cv_regsem function. Then I compared the chisq value at lambda = 0 with the chisq value of the original model.

```{r }
library(regsem)
library(lavaan)
## The industrialization and Political Democracy Example 
## Bollen (1989), page 332
model <- ' 
  # latent variable definitions
     ind60 =~ x1 + x2 + x3
     dem60 =~ y1 + y2 + y3 + y4
     dem65 =~ y5 + y6 + y7 + y8
'

# define missing values 
PoliticalDemocracy[1,1] <- NA
PoliticalDemocracy[2,5] <- NA
PoliticalDemocracy[3,2] <- NA
PoliticalDemocracy[20,6] <- NA
PoliticalDemocracy[70,7] <- NA
PoliticalDemocracy[60,11] <- NA

fit <- sem(model,
           data = PoliticalDemocracy,
           missing = "fiml")
fitMeasures(fit, "chisq")
coef(fit)

fit_regsem <- cv_regsem(model = fit,
                        n.lambda = 1,
                        pars_pen = 1)
fit_regsem$fits[1,"chisq"]
fit_regsem$parameters[1,]

# Using fiml as missing results in error
fit_regsem <- cv_regsem(model = fit,
                        n.lambda = 1,
                        pars_pen = 1,
                        missing = "fiml")
```
If I run this example, you can see that chisq values differ at the end (70.885 vs. 72.3704). The missing argument in the cv_regsem function does provide the FIML, but then I get an error message.  Did I do something wrong or is there another way to deal with missing values? 

Best,
Britta Sprank

**Comment by Rjacobucci** [comment]
Hi Britta,

No, it's nothing on your part. Its been years since the missing option has been revised, so I'm not at all surprised that issues are occurring. Given recent developments, I'd recommend using MPlus or OpenMx, as both now have regularization options, and much more thorough development with respect to missingness.

Best,
Ross
